name: Python Linting

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - "**/*.py"

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      # Step 4: Run flake8 for linting
      - name: Run flake8 linter
        run: |
          # flake8 will automatically discover and use the .flake8 configuration file
          flake8 .

      # Step 5: Run black in check mode
      - name: Run black (format check)
        run: |
          echo "Running black formatting check..."
          black --check .

      # Step 6: Report success
      - name: Report success
        if: ${{ success() }}
        run: echo "✅ All Python lint checks passed successfully!"
