name: Stale Issue Reminder

on:
  schedule:
    # run daily at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-labels: 'in-progress'
        days-before-stale: 2
        days-before-close: 1
        stale-issue-label: 'stale'
        #ignore PRs
        days-before-pr-stale: -1
        days-before-pr-close: -1
        
        #warning comment
        stale-issue-message: |
          This issue has been labeled as `stale` because it has been open for 48 hours with no activity. If you are still working on this, please leave a comment to let us know. Otherwise, this issue will be closed in 24 hours. Thank you for your contribution!
        
        #close comment
        close-issue-message: |
          This issue is being closed because it has been inactive for 72 hours. If you would like to continue working on this, please feel free to re-open the issue and leave a comment!
        
        remove-issue-stale-when-updated: true
        debug-only: false